### ISSUE TITLE
[ginsim] <GINsim Model>.getEdges() crashes py4j gateway

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-jupyter#2]
```
import ginsim
m = ginsim.open("model.zginml")
m.getEdges()
```

**Comment by aurelien-naldi** [comment]
This works fine as a "normal" GINsim script (using Jython instead of Py4J).
The following line works:
edges = m.getEdges()

but it seems to be stuck in an infinite loop if we iterate over the result (which works fine in jython):
for e in edges:
   print(e)

The returned object is a custom implementation of the Set interface (edges are stored as linked list in each node metadata, this provides a view in a single Collection). It probably misses something to be mapped to a Python collection.

**Comment by aurelien-naldi** [comment]
I found the culprit: java iterators have a "boolean hasNext()" and "Object next()" methods.
All my code, and java loops stop when hasNext() returns false, but Py4J relies on the fact that the next call to next should throw an exception instead of returning null...
I fixed this iterator in GINsim, I probably have a few others ones with the same problem

**Comment by aurelien-naldi** [comment]
It should be fully solved with the next uploads: I searched and fixed other custom iterators in GINsim and bioLQM
